# array的创建及访问

In [1]:
import numpy as np

In [2]:
list_1 = [1, 2, 3, 4]
list_1

[1, 2, 3, 4]

In [3]:
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [4]:
list_2 = [5, 6, 7, 8]

In [5]:
array_2 = np.array([list_1, list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
array_2.shape

(2, 4)

In [7]:
array_2.size

8

In [8]:
array_2.dtype

dtype('int32')

In [9]:
array_3 = np.array([[1., 2., 3., 4.],[5., 6., 7., 8.]])

In [10]:
array_3.dtype

dtype('float64')

In [11]:
array_4 = np.arange(1, 10, 2)
array_4

array([1, 3, 5, 7, 9])

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
array_5 = np.arange(1, 10).reshape(3, -1)
array_5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
array_5[:2, 1:]

array([[2, 3],
       [5, 6]])

# 数组与矩阵运算

In [17]:
np.random.randn(10)

array([ 0.44521783,  0.14522892, -0.9786945 , -0.1925035 , -0.65886157,
       -0.65555632, -1.61585491, -0.26475772,  1.18583704, -0.87024396])

In [18]:
np.random.randint(10, size=(3,4))

array([[5, 7, 7, 6],
       [4, 5, 6, 7],
       [2, 1, 9, 6]])

In [19]:
a = np.random.randint(10, size=(4,5))
a

array([[9, 0, 4, 1, 2],
       [3, 4, 6, 6, 3],
       [5, 6, 7, 8, 6],
       [1, 5, 0, 1, 5]])

In [20]:
b = np.random.randint(10, size=(4,5))
b

array([[6, 4, 9, 3, 7],
       [1, 9, 3, 8, 4],
       [1, 7, 4, 8, 0],
       [8, 3, 5, 9, 4]])

### 数组运算

In [21]:
a + b

array([[15,  4, 13,  4,  9],
       [ 4, 13,  9, 14,  7],
       [ 6, 13, 11, 16,  6],
       [ 9,  8,  5, 10,  9]])

In [22]:
a - b

array([[ 3, -4, -5, -2, -5],
       [ 2, -5,  3, -2, -1],
       [ 4, -1,  3,  0,  6],
       [-7,  2, -5, -8,  1]])

In [23]:
a * b

array([[54,  0, 36,  3, 14],
       [ 3, 36, 18, 48, 12],
       [ 5, 42, 28, 64,  0],
       [ 8, 15,  0,  9, 20]])

In [24]:
a / b

<ipython-input-24-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in true_divide
  a / b


array([[1.5       , 0.        , 0.44444444, 0.33333333, 0.28571429],
       [3.        , 0.44444444, 2.        , 0.75      , 0.75      ],
       [5.        , 0.85714286, 1.75      , 1.        ,        inf],
       [0.125     , 1.66666667, 0.        , 0.11111111, 1.25      ]])

### 矩阵运算

In [25]:
np.mat([[1, 2, 3], [4, 5, 6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [26]:
np.mat(a)

matrix([[9, 0, 4, 1, 2],
        [3, 4, 6, 6, 3],
        [5, 6, 7, 8, 6],
        [1, 5, 0, 1, 5]])

In [27]:
A = np.mat(a)
A

matrix([[9, 0, 4, 1, 2],
        [3, 4, 6, 6, 3],
        [5, 6, 7, 8, 6],
        [1, 5, 0, 1, 5]])

In [28]:
B = np.mat(b)
B

matrix([[6, 4, 9, 3, 7],
        [1, 9, 3, 8, 4],
        [1, 7, 4, 8, 0],
        [8, 3, 5, 9, 4]])

In [29]:
A + B

matrix([[15,  4, 13,  4,  9],
        [ 4, 13,  9, 14,  7],
        [ 6, 13, 11, 16,  6],
        [ 9,  8,  5, 10,  9]])

In [30]:
A - B

matrix([[ 3, -4, -5, -2, -5],
        [ 2, -5,  3, -2, -1],
        [ 4, -1,  3,  0,  6],
        [-7,  2, -5, -8,  1]])

In [31]:
B = np.mat(b).reshape(5, -1)

In [32]:
A * B

matrix([[ 96,  70, 103,  71],
        [127, 103,  96, 123],
        [178, 148, 160, 170],
        [ 60,  42,  99,  46]])

### array常用函数

In [33]:
a = np.random.randint(10, size=(4,5))
a

array([[6, 0, 2, 7, 0],
       [1, 7, 8, 2, 4],
       [1, 0, 3, 7, 2],
       [7, 4, 8, 8, 9]])

In [34]:
np.unique(a)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [35]:
sum(a)

array([15, 11, 21, 24, 15])

In [36]:
sum(a[0])

15

In [37]:
sum(a[:,0])

15

In [38]:
a.max()

9

In [39]:
max(a[0])

7

In [40]:
max(a[:,0])

7

# array的input和output

In [41]:
import pickle

In [42]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
f = open('x.pkl', 'wb')
pickle.dump(x, f)

In [44]:
f = open('x.pkl', 'rb')

In [45]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.save("one_array", x)

In [47]:
np.load("one_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
np.savez("two_array.npz", a=x, b=y)

In [50]:
c = np.load("two_array.npz")

In [51]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])