In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# series和dataframe的简单数学计算

In [2]:
s1 = Series([1, 2, 3], index=["A", "B", "C"])
s1

A    1
B    2
C    3
dtype: int64

In [3]:
s2 = Series([4, 5, 6, 7], index=["B", "C", "D", "E"])
s2

B    4
C    5
D    6
E    7
dtype: int64

In [4]:
s1 + s2

A    NaN
B    6.0
C    8.0
D    NaN
E    NaN
dtype: float64

In [5]:
df1 = DataFrame(np.arange(4).reshape(2, -1), index=["A", "B"], columns=["BJ", "SH"])
df1

BJ  SH
A   0   1
B   2   3

In [6]:
df2 = DataFrame(np.arange(9).reshape(3, -1), index=["A", "B", "C"], columns=["BJ", "SH", "GZ"])
df2

BJ  SH  GZ
A   0   1   2
B   3   4   5
C   6   7   8

In [7]:
df1 + df2

BJ  GZ   SH
A  0.0 NaN  2.0
B  5.0 NaN  7.0
C  NaN NaN  NaN

In [8]:
df3 = DataFrame([[1, 2, 3],[4, 5, np.nan],[7, 8, 9]], index=["A", "B", "C"], columns=["C1", "C2", "C3"])
df3

C1  C2   C3
A   1   2  3.0
B   4   5  NaN
C   7   8  9.0

In [9]:
df3.sum()

C1    12.0
C2    15.0
C3    12.0
dtype: float64

In [10]:
df3.sum(axis=1)

A     6.0
B     9.0
C    24.0
dtype: float64

In [11]:
df3.min()

C1    1.0
C2    2.0
C3    3.0
dtype: float64

In [12]:
df3.describe()

C1   C2        C3
count  3.0  3.0  2.000000
mean   4.0  5.0  6.000000
std    3.0  3.0  4.242641
min    1.0  2.0  3.000000
25%    2.5  3.5  4.500000
50%    4.0  5.0  6.000000
75%    5.5  6.5  7.500000
max    7.0  8.0  9.000000

# series和dataframe的排序

In [13]:
s1 = Series(np.random.randn(10))
s1

0    0.364185
1    0.978439
2    1.796577
3   -1.302526
4    1.284109
5   -0.324577
6    0.567757
7    0.712222
8   -1.988094
9   -0.335085
dtype: float64

In [14]:
s1.sort_values()

8   -1.988094
3   -1.302526
9   -0.335085
5   -0.324577
0    0.364185
6    0.567757
7    0.712222
1    0.978439
4    1.284109
2    1.796577
dtype: float64

In [16]:
s1.sort_index(ascending=False)

9   -0.335085
8   -1.988094
7    0.712222
6    0.567757
5   -0.324577
4    1.284109
3   -1.302526
2    1.796577
1    0.978439
0    0.364185
dtype: float64

In [18]:
df1 = DataFrame(np.random.randn(40).reshape(8, -1), columns=["A","B","C","D","E"])
df1

A         B         C         D         E
0 -0.050698 -0.013272 -0.162769 -0.274841 -0.851623
1  0.498418 -1.413137  0.172984 -1.074943 -0.815542
2 -0.379288  0.643006 -2.375315  0.382894  0.361180
3 -0.173708  0.351830  0.039590  0.456057 -0.304799
4  0.364250 -1.124963  0.226051 -2.396640  0.158312
5  0.725536  1.080984  1.188750  0.223831 -0.199636
6 -1.269076  0.479465 -0.253253 -0.655904  0.404385
7  0.126784  1.408595 -0.019438 -1.068250 -0.957358

In [20]:
df1["A"].sort_values()

6   -1.269076
2   -0.379288
3   -0.173708
0   -0.050698
7    0.126784
4    0.364250
1    0.498418
5    0.725536
Name: A, dtype: float64

In [21]:
df1.sort_values("A")

A         B         C         D         E
6 -1.269076  0.479465 -0.253253 -0.655904  0.404385
2 -0.379288  0.643006 -2.375315  0.382894  0.361180
3 -0.173708  0.351830  0.039590  0.456057 -0.304799
0 -0.050698 -0.013272 -0.162769 -0.274841 -0.851623
7  0.126784  1.408595 -0.019438 -1.068250 -0.957358
4  0.364250 -1.124963  0.226051 -2.396640  0.158312
1  0.498418 -1.413137  0.172984 -1.074943 -0.815542
5  0.725536  1.080984  1.188750  0.223831 -0.199636

In [22]:
imdb = pd.read_csv("D:/资料/机器学习/数据资料/imdb/movie_metadata.csv")[['director_name', 'movie_title', 'imdb_score']]
imdb

director_name                                        movie_title  imdb_score
0         James Cameron                                            Avatar          7.9
1        Gore Verbinski          Pirates of the Caribbean: At World's End          7.1
2            Sam Mendes                                           Spectre          6.8
3     Christopher Nolan                             The Dark Knight Rises          8.5
4           Doug Walker  Star Wars: Episode VII - The Force Awakens    ...         7.1
...                 ...                                                ...         ...
5038        Scott Smith                           Signed Sealed Delivered          7.7
5039                NaN                         The Following                      7.5
5040   Benjamin Roberds                              A Plague So Pleasant          6.3
5041        Daniel Hsia                                  Shanghai Calling          6.3
5042           Jon Gunn                                 My Date with Drew          6.6

[5043 rows x 3 columns]

In [28]:
imdb.sort_values("imdb_score", ascending=False)

director_name                      movie_title  imdb_score
2765        John Blanchard    Towering Inferno                      9.5
1937        Frank Darabont        The Shawshank Redemption          9.3
3466  Francis Ford Coppola                   The Godfather          9.2
4409        John Stockwell            Kickboxer: Vengeance          9.1
2824                   NaN             Dekalog                      9.1
...                    ...                              ...         ...
2268       Jason Friedberg                  Disaster Movie          1.9
2295             Bob Clark    Superbabies: Baby Geniuses 2          1.9
4605         A. Raven Cruz             The Helix... Loaded          1.9
1136     Lawrence Kasanoff                      Foodfight!          1.7
2834            Jon M. Chu  Justin Bieber: Never Say Never          1.6

[5043 rows x 3 columns]

# 重命名dataframe的index

In [29]:
df1 = DataFrame(np.arange(9).reshape(3, -1), columns=["A", "B", "C"], index=["BJ", "SH", "GZ"])
df1

A  B  C
BJ  0  1  2
SH  3  4  5
GZ  6  7  8

In [30]:
df1.index

Index(['BJ', 'SH', 'GZ'], dtype='object')

In [31]:
df1.index = Series(["bj", "sh", "sz"])
df1

A  B  C
bj  0  1  2
sh  3  4  5
sz  6  7  8

In [33]:
df1.index = df1.index.map(str.upper)
df1

A  B  C
BJ  0  1  2
SH  3  4  5
SZ  6  7  8

In [37]:
df1.rename(index=str.lower, columns=str.lower)

a  b  c
bj  0  1  2
sh  3  4  5
sz  6  7  8

In [36]:
df1

A  B  C
BJ  0  1  2
SH  3  4  5
SZ  6  7  8

In [38]:
df1.rename(index={"BJ":"beijing"}, columns={"A":"a"})

a  B  C
beijing  0  1  2
SH       3  4  5
SZ       6  7  8

In [39]:
list1 = [1, 2, 3, 4]
list2 = ['1', '2', '3', '4']

In [40]:
[str(x) for x in list1]

['1', '2', '3', '4']

In [41]:
list(map(str, list1))

['1', '2', '3', '4']

In [42]:
df1

A  B  C
BJ  0  1  2
SH  3  4  5
SZ  6  7  8

In [43]:
def test_map(x):
    return x + '_WHK'

In [44]:
df1.index.map(test_map)

Index(['BJ_WHK', 'SH_WHK', 'SZ_WHK'], dtype='object')

In [45]:
df1.rename(index=test_map)

A  B  C
BJ_WHK  0  1  2
SH_WHK  3  4  5
SZ_WHK  6  7  8

# dataframe的merge操作

In [3]:
df1 = DataFrame({"key":['X', 'Y', 'Z'], "data_set_1":[1, 2, 3]})
df1

key  data_set_1
0   X           1
1   Y           2
2   Z           3

In [5]:
df2 = DataFrame({"key":['A', 'B', 'C'], "data_set_2":[4, 5, 6]})
df2

key  data_set_2
0   A           4
1   B           5
2   C           6

In [6]:
pd.merge(df1, df2)

Empty DataFrame
Columns: [key, data_set_1, data_set_2]
Index: []

In [7]:
df3 = DataFrame({"key":['X', 'Y', 'Z'], "data_set_3":[4, 5, 6]})
df3

key  data_set_3
0   X           4
1   Y           5
2   Z           6

In [8]:
pd.merge(df1, df3)

key  data_set_1  data_set_3
0   X           1           4
1   Y           2           5
2   Z           3           6

In [13]:
df4 = DataFrame({"key":['X', 'B', 'C'], "data_set_4":[4, 5, 6]})
df4

key  data_set_4
0   X           4
1   B           5
2   C           6

In [14]:
pd.merge(df1, df4)

key  data_set_1  data_set_4
0   X           1           4

# concatenate 和 combine

In [15]:
arr1 = np.arange(9).reshape(3, -1)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr2 = np.arange(9).reshape(3, -1)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.concatenate([arr1, arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.concatenate([arr1, arr2], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [20]:
np.concatenate([arr1, arr2], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
s1 = Series([1, 2, 3], index=["X", "Y", "Z"])
s1

X    1
Y    2
Z    3
dtype: int64

In [22]:
s2 = Series([4, 5], index=["A", "B"])
s2

A    4
B    5
dtype: int64

In [23]:
pd.concat([s1, s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [24]:
pd.concat([s1, s2], axis=1)

0    1
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN
A  NaN  4.0
B  NaN  5.0

In [25]:
pd.concat([s1, s2], axis=0)

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [26]:
df1 = DataFrame(np.random.randn(4,3), columns=["X","Y","Z"])
df1

X         Y         Z
0 -1.450750  0.079893  0.936846
1  2.179759  2.770651 -0.662780
2 -0.955592  0.064788 -1.450144
3 -1.379326  1.273617 -0.607569

In [27]:
df2 = DataFrame(np.random.randn(3,3), columns=["X","Y","A"])
df2

X         Y         A
0  1.725471  1.166545  1.301753
1  0.134283 -0.961731 -0.418625
2 -1.360369 -0.745914 -0.264182

In [29]:
pd.concat([df1, df2])

X         Y         Z         A
0 -1.450750  0.079893  0.936846       NaN
1  2.179759  2.770651 -0.662780       NaN
2 -0.955592  0.064788 -1.450144       NaN
3 -1.379326  1.273617 -0.607569       NaN
0  1.725471  1.166545       NaN  1.301753
1  0.134283 -0.961731       NaN -0.418625
2 -1.360369 -0.745914       NaN -0.264182

In [30]:
pd.concat([df1, df2], axis=1)

X         Y         Z         X         Y         A
0 -1.450750  0.079893  0.936846  1.725471  1.166545  1.301753
1  2.179759  2.770651 -0.662780  0.134283 -0.961731 -0.418625
2 -0.955592  0.064788 -1.450144 -1.360369 -0.745914 -0.264182
3 -1.379326  1.273617 -0.607569       NaN       NaN       NaN

### combine

In [31]:
s1 = Series([2, np.nan, 4, np.nan], index=["A","B","C","D"])
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [33]:
s2 = Series([1, 2, 3, 4], index=["A","B","C","D"])
s2

A    1
B    2
C    3
D    4
dtype: int64

In [34]:
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [37]:
df1 = DataFrame({
    'X':[1, np.nan, 3, np.nan],
    'Y':[5, np.nan, 7, np.nan],
    'Z':[9, np.nan, 11, np.nan]
})
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [38]:
df2 = DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1, 2, 3, 4]
})
df2

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [39]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0

# 通过apply进行数据预处理

In [42]:
df = pd.read_csv("D:/资料/机器学习/数据资料/imdb/apply_demo.csv")
df.head()

time                                data
0  1473411962   Symbol: APPL Seqno: 0 Price: 1623
1  1473411962   Symbol: APPL Seqno: 0 Price: 1623
2  1473411963   Symbol: APPL Seqno: 0 Price: 1623
3  1473411963   Symbol: APPL Seqno: 0 Price: 1623
4  1473411963   Symbol: APPL Seqno: 1 Price: 1649