In [2]:
import numpy as np

In [3]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
ind = [3, 5, 8]

In [5]:
x[ind]

array([3, 5, 8])

In [6]:
ind = np.array([[0, 2],
                [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [7]:
x = x.reshape(4, -1)

In [8]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])