In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
nparr = np.arange(15)

In [4]:
nparr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
nparr[5]

5

In [6]:
nparr[5] = 100

In [7]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [8]:
nparr[5] = "ML"

ValueError: invalid literal for int() with base 10: 'ML'

In [9]:
nparr.dtype

dtype('int32')

In [10]:
nparr[5] = 8.5
nparr

array([ 0,  1,  2,  3,  4,  8,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
nparr2 = np.array([1, 2, 3.0])
nparr2

array([1., 2., 3.])

In [12]:
nparr2.dtype

dtype('float64')

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])