In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
raw_data_x = [[1.564564434, 2.54564634566], 
              [1.465646456, 2.45646878646], 
              [2.456456787, 2.77864568658], 
              [2.543445212, 2.54567832437], 
              [1.578312378, 2.57864537867],
              [4.867278774, 2.78672437867], 
              [4.787867458, 2.58736837673], 
              [5.783245367, 2.57867416348], 
              [5.784236743, 2.73786783786], 
              [4.567831389, 2.52876786786]]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

x_train = np.array(raw_data_x)
y_train = np.array(raw_data_y)

In [ ]:
plt.scatter(x_train[y_train==0,0], x_train[y_train==0,1], color="g")
plt.scatter(x_train[y_train==1,0], x_train[y_train==1,1], color="r")
plt.show()

In [ ]:
x = np.array([4.784236743, 2.73786783786])

In [ ]:
plt.scatter(x_train[y_train==0,0], x_train[y_train==0,1], color="g")
plt.scatter(x_train[y_train==1,0], x_train[y_train==1,1], color="r")
plt.scatter(x[0], x[1], color="b")
plt.show()

In [ ]:
%run knn00.py

In [ ]:
pred_y = knn_classify(6, x_train, y_train, x)
pred_y

### 使用scikit-learn中的KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train, y_train)

In [ ]:
knn.predict(x.reshape(1, -1))

### 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [5]:
iris = datasets.load_iris()

X = iris.data
y = iris.target
print(X.shape)
print(y.shape)

(150, 4)
(150,)


### train_test_split

In [6]:
shuffle_index = np.random.permutation(len(X))
shuffle_index

array([ 87,  55, 128,  13,  69, 129,   9, 107,  34,  82, 139, 136,  20,
        74,  30, 108, 130, 106,  96, 114, 109, 131,  41,  85,  86,  58,
        49, 148,  42,  68,  67, 125, 141,  63,   2, 120, 140,  60, 122,
        36,  83,   3,  81, 116,  79,  72,  95,  56,  65,   6,   4, 110,
       112,  31,  40, 126,  98,  37, 121,   1,  57,  70, 111, 147,  76,
        71,  44,  10, 105,  39,   8,  48,  84, 149,  21,  29,  38, 113,
       143,  25,  24,  19, 119,  15,  45, 137,  46, 102,  61,  73,  77,
       133,  89,   0, 135,  78,  26,  33, 104,   5, 101,  14, 142, 145,
       117,  91,  54, 127, 144, 123,  47,  16,  88,  59,  22,  18,  51,
        66, 103,  23, 124,  99, 100,  50,  17,  52,  90,  75,   7,  12,
        43,  80,  35, 146,  64, 132,  11,  27,  32,  94,  92,  97,  93,
       138, 134,  62,  53,  28, 118, 115])

In [7]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)
test_size

30

In [8]:
train_index = shuffle_index[test_size:]
test_index = shuffle_index[:test_size]

In [9]:
X_train = X[train_index]
y_train = y[train_index]

X_test = X[test_index]
y_test = y[test_index]

In [10]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


### 使用自己的算法

In [16]:
from playML.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [22]:
from playML.kNN import KNNClassifier

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [23]:
my_knn = KNNClassifier(k=3)
my_knn.fit(X_train, y_train)
y_pred = my_knn.predict(X_test)
y_pred

array([2, 0, 2, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 1, 0, 0, 2, 0, 0, 1, 2, 1,
       0, 2, 0, 1, 1, 2, 1, 2])

In [24]:
y_test

array([2, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 1, 0, 0, 2, 0, 0, 1, 2, 1,
       0, 2, 0, 1, 1, 2, 1, 2])

In [26]:
sum(y_pred == y_test)

29

In [27]:
sum(y_pred == y_test)/len(y_test)

0.9666666666666667

### scikit-learn中的train_test_split

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y)
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)
print(y_test)
print(pred)

[1 2 1 0 1 2 0 2 0 1 0 2 0 2 1 0 0 0 2 2 2 2 2 0 0 1 1 2 0 0 1 1 2 2 0 1 0
 1]
[1 2 1 0 1 2 0 2 0 1 0 1 0 2 1 0 0 0 2 2 2 2 2 0 0 1 1 2 0 0 1 1 2 2 0 1 0
 1]


In [36]:
sum(pred == y_test)/len(y_test)

1.0

In [39]:
score = knn.score(X_test, y_test)
score

0.9736842105263158